### ISSUE TITLE
purpose for token in database?

### ISSUE THREAD

**Issue by osseonews** [aagam29/next-auth-patterns-demo#1]
Thanks for the great demo. What I don't understand is why you are storing the JWT token in the database. When the user signs up, you create a JWT token that is stored in the database. But this JWT is never used, because when you sign in the user, you create a new  JWT and store it in the database replacing the JWT that was created upon sign up, negating any use of the JWT that was originoally stored. Plus the JWT that is created upon signin is stored in cookie with Ironsession and verified via the header that is sent to the server (jwt.verify), and so what is the point of storing the JWT in the database at all? Thanks.

**Comment by aagam29** [comment]
To keep the scope smaller, I have kept it open-ended and stored the latest token just in case anyone wants to build further on this. For many applications, users can have multiple logins on the web apps, mobile apps, for multiple devices.
We can store the tokens in DB so that we can use it to manage multiple logins, revoking access, etc. 
Of course, that will require changing the sign-in and other flows and has not been implemented in this repo to keep it simple. So, depending on the use case you can choose to store or not store the token in DB and it is also okay to not store the token in DB.
